RentVehicle/Account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views#For Login and Logout views
#We need not create class for them
from . import views

app_name = 'Account'

urlpatterns = [
    #path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("RenterSignUp/", views.RenterSignUp, name="RenterSignUp"),
    path("OwnerSignUp/", views.OwnerSignUp, name="OwnerSignUp"),
    path("RenterLogIn/", views.RenterLogin, name="RenterLogIn"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("OwnerLogIn/", views.OwnerLogin, name="OwnerLogIn"),
]

RentVehicle/Owner/urls.py
from django.urls import path
from . import views

app_name = 'Owner'

urlpatterns = [
    path("OwnerVehicles/", views.ListOwnerVehicles.as_view(), name="OwnerVehicles"),
    path("AddVehicle/",views.CreateVehicle.as_view(),name = 'CreateVehicle'),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    path("requests/", views.RequestList.as_view(), name = "RequestList"),
    path('requests/<int:pk>', views.RequestDetails.as_view(), name='RequestDetails'),
    path("Owner/Feedback/<VehicleRegistrationNumber>/<int:pk>",views.OwnerFeedback.as_view(), name = "OwnerFeedback"),
    path("Report/Accident/<int:pk>",views.ReportAccident.as_view(), name = "ReportAccident"),
    path("Enable/The/Vehicle/<int:pk>",views.EnableVehicle.as_view(), name = "EnableVehicle"),
]

RentVehicle/RentVehicle/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name = 'home'),
    path('SignUp/',views.SignUp, name = 'SignUp'),
    path('LogIn/',views.LogIn, name = 'LogIn'),
    path("accounts/", include("Account.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('vehicle/',include("Vehicle.urls", namespace="vehicles")),
    path("owner/", include("Owner.urls", namespace="owner")),
    path("renter/", include("Renter.urls", namespace="renter")),
    path("booking/", include("Booking.urls", namespace="booking")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RentVehicle/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Rent Vehicle</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'RentVehicle/CSS/master.css'%}">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'home' %}">Rent Vehicle</a>
        </div>
        <div class="nav navbar-nav">
          {% if user.is_authenticated %}
            {% block Navigation %} {%endblock%}
            <a class="nav-item nav-link" href="{% url 'Account:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'LogIn' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'SignUp' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <canvas id="canvas1"></canvas>

    <script src="{% static "RentVehicle/JS/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

RentVehicle/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <h1><font color = "Black">Welcome to RentVehicle!</font></h1>
  <form method="POST">
    {% csrf_token %}
    {{error}}
    <font color = "black">{{form.as_p}}</font>
    <input type="submit" name="" value="Submit">
  </form>
</div>

{% endblock %}

RentVehicle/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1><font color = "black">Log In as Renter or Owner</font></h1>
  <a href="{%url 'Account:RenterLogIn'%}">
    <button type="button" name="btn btn-success">
      Renter
    </button>
  </a>
  <a href="{%url 'Account:OwnerLogIn'%}">
    <button type="button" name="btn btn-success">
      Owner
    </button>
  </a>

</div>

{% endblock %}

RentVehicle/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1><font color = "black">Sign Up as Renter or Owner</font></h1>
  <a href="{%url 'Account:RenterSignUp'%}">
    <button type="button" name="btn btn-primary">
      Renter
    </button>
  </a>
  <a href="{%url 'Account:OwnerSignUp'%}">
    <button type="button" name="btn btn-primary">
      Owner
    </button>
  </a>
  </div>

{% endblock %}

RentVehicle/templates/test.html
{% extends 'base.html' %}

{% block content %}
  <h1>You are now logged in</h1>
{% endblock %}

RentVehicle/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <h1>Thanks for visiting. Comeback soon!</h1>
{% endblock %}