RentVehicle/Booking/urls.py
from django.urls import path
from . import views

app_name='Booking'

urlpatterns = [
    path('<VehicleRegistrationNumber>/<int:pk>', views.CreateBooking.as_view(), name="CreateBooking"),
    path('RenterBooking/',views.RenterBookingList.as_view(), name="RenterBookingList"),
    path('OwnerBookingList/',views.OwnerBookingList.as_view(), name="OwnerBookingList"),
    path('<int:pk>', views.RenterBookingDetails.as_view(), name='RenterBookingDetails'),
    path('Owner/Booking/Details<int:pk>', views.OwnerBookingDetails.as_view(), name='OwnerBookingDetails'),
    path('OldBooking/Details/<int:pk>', views.OldBookingDetails.as_view(), name='OldBookingDetails'),
    path('<int:pk>/SelectPayment', views.SelectPayment.as_view(), name='SelectPayment'),
    path('MakePayment/PayByCard/<int:pk>', views.CardPayment.as_view(), name='CardPayment'),
    path('MakePayment/PayByCheck/<int:pk>', views.CheckPayment.as_view(), name='CheckPayment'),
]

RentVehicle/Owner/urls.py
from django.urls import path
from . import views

app_name = 'Owner'

urlpatterns = [
    path("OwnerVehicles/", views.ListOwnerVehicles.as_view(), name="OwnerVehicles"),
    path("AddVehicle/",views.CreateVehicle.as_view(),name = 'CreateVehicle'),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    path("requests/", views.RequestList.as_view(), name = "RequestList"),
    path('requests/<int:pk>', views.RequestDetails.as_view(), name='RequestDetails'),
    path("Owner/Feedback/<VehicleRegistrationNumber>/<int:pk>",views.OwnerFeedback.as_view(), name = "OwnerFeedback"),
    path("Report/Accident/<int:pk>",views.ReportAccident.as_view(), name = "ReportAccident"),
    path("Enable/The/Vehicle/<int:pk>",views.EnableVehicle.as_view(), name = "EnableVehicle"),
]

RentVehicle/RentVehicle/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name = 'home'),
    path('SignUp/',views.SignUp, name = 'SignUp'),
    path('LogIn/',views.LogIn, name = 'LogIn'),
    path("accounts/", include("Account.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('vehicle/',include("Vehicle.urls", namespace="vehicles")),
    path("owner/", include("Owner.urls", namespace="owner")),
    path("renter/", include("Renter.urls", namespace="renter")),
    path("booking/", include("Booking.urls", namespace="booking")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RentVehicle/Vehicle/urls.py
from django.urls import path
from . import views

app_name='Vehicle'

urlpatterns = [
    path('', views.VehicleList.as_view(), name="all"),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    #path('add/', views.CreateVehicle.as_view(), name='addVehicle')
    #path("new/", views.CreateVehicle.as_view(), name="create"),
    #path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    #path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    #path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

RentVehicle/Owner/forms.py
from Vehicle import models
from . import models as omodels
from django import forms

class VehicleCreate(forms.ModelForm):
    class Meta:
        model = models.Vehicle
        exclude = ['user','rating']

class AcceptRejectForm(forms.ModelForm):
    class Meta:
        model = omodels.AcceptRejectBooking
        fields = ['value']

class GetFeedback(forms.ModelForm):
    class Meta:
        model = omodels.RenterFeedback
        fields = ['rating','description']

class AccidentReport(forms.ModelForm):
    class Meta:
        model = models.Accident
        fields = ['disabled','description']

RentVehicle/Vehicle/forms.py
from Vehicle import models
from django import forms
from dropdowndb.models import ZipCode
import datetime

class CreateFilter(forms.ModelForm):
    class Meta:
        model = models.Filter
        fields = ['zipcode', 'make', 'color', 'StartPrice', 'EndPrice', 'rating','style','bookingDate']


    def __init__(self, *args,**kwargs):
        super(CreateFilter, self).__init__(*args, **kwargs)
        filter = models.Filter.objects.get(user=None)
        print("Here")
        self.fields['bookingDate'].label = 'Date'
        self.fields['zipcode'].initial = filter.zipcode
        self.fields['make'].initial = filter.make
        self.fields['color'].initial = filter.color
        self.fields['StartPrice'].initial = filter.StartPrice
        self.fields['EndPrice'].initial = filter.EndPrice
        self.fields['rating'].initial = filter.rating
        self.fields['style'].initial = filter.style
        self.fields['bookingDate'].initial = filter.bookingDate
        self.fields['zipcode'].required = False
        self.fields['make'].required = False
        self.fields['color'].required = False
        self.fields['StartPrice'].required = False
        self.fields['EndPrice'].required = False
        self.fields['rating'].required = False
        self.fields['style'].required = False
        self.fields['bookingDate'].required = False

    def clean_bookingDate(self):
        bookingdate = self.cleaned_data.get('bookingDate')
        if(bookingdate):
            if(bookingdate < datetime.date.today()):
                raise forms.ValidationError("Booking date has to be future date")
        return bookingdate

RentVehicle/Owner/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views import generic
from Vehicle import models
from Booking import models as bmodels
from . import forms
from django.http import Http404
from dropdowndb import models as dmodels
from . import models as omodels
import datetime

# Create your views here.
class ListOwnerVehicles(generic.ListView):
    model = models.Vehicle
    template_name = 'Owner/OwnerVehicle_List.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            self.vehicle = models.Vehicle.objects.filter(
                user = self.request.user
            )
            try:
                Accident_vehicle = models.Accident.objects.filter(
                    disabled = True
                ).values()
                if len(Accident_vehicle) > 0:
                    Accident_vehicle_list = []
                    for av in Accident_vehicle:
                        Accident_vehicle_list.append(av['vehicle_id'])
                    self.vehicle = self.vehicle.filter(
                        pk__in = Accident_vehicle_list
                    )
                    context['vehicle'] = self.vehicle
                return context
            except Exception as e:
                print(type(e))
                print("In except")
                return context
        except Exception as e:
            print(type(e))
            print("In except")
            return context

    def get_queryset(self):
        try:
            self.vehicles = models.Vehicle.objects.filter(
                user = self.request.user
            )
            try:
                Accident_vehicle = models.Accident.objects.filter(
                    disabled = True
                ).values()
                for av in Accident_vehicle:
                    self.vehicles = self.vehicles.exclude(
                    pk = av['vehicle_id']
                    )
            except:
                pass
        except Exception as e:
            print (type(e))
            return ""
        else:
            return self.vehicles.all()

class CreateVehicle(generic.CreateView):
    form_class = forms.VehicleCreate
    model = models.Vehicle
    template_name = "Owner/vehicle_form.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.rating = 0
        if 'image' in self.request.FILES:
            self.object.image = self.request.FILES['image']
            print("Here")
        self.object.save()
        return super().form_valid(form)

class VehicleDetails(generic.DetailView):
    model = models.Vehicle
    template_name = "Owner/OwnerVehicle_Detail.html"
    context_object_name = "vehicle_detail"

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(
    #         VehicleRegistrationNumber = self.kwargs.get("VehicleRegistrationNumber")
    #     )
        # try:
        #     vehicle = models.Vehicle.objects.get(
        #         VehicleRegistrationNumber = self.kwargs.get("VehicleRegistrationNumber")
        #     )
        # except Exception as e:
        #     print (type(e))
        #     return ""
        # else:
        #     return self.vehicles.all()

class RequestList(generic.ListView):
    model = bmodels.Booking
    template_name = "Owner/request_list.html"
    context_object_name = 'request_list'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(
            vehicle__user = self.request.user
        )
        return queryset.filter(
            requestStatus__statusId = 1
        ).filter(
            bookingDate__gte = datetime.date.today()
        )

class RequestDetails(generic.DetailView):
    model = bmodels.Booking
    form = forms.AcceptRejectForm()
    template_name = 'Owner/request_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form
        try:
            booking = bmodels.Booking.objects.get(pk=self.kwargs.get('pk'))
            negotiationRequest = booking.negotiationRequest
            context["negotiationRequest"] = negotiationRequest
            feedback = omodels.RenterFeedback.objects.filter(booking__user = booking.user)
            context['feedback'] = feedback
        except:
            return context
        return context

    def post(self, request, *args, **kwargs):
        filter_form = forms.AcceptRejectForm(data = request.POST)
        if filter_form.is_valid():
            filterForm = filter_form.save(commit=False)
            booking = bmodels.Booking.objects.get(pk=self.kwargs.get('pk'))
            if filterForm.value == dmodels.AcceptRejectBooking.objects.get(pk=1):
                booking.requestStatus = dmodels.RequestStatus.objects.get(statusId=3)
            else:
                booking.requestStatus = dmodels.RequestStatus.objects.get(statusId=2)
            if self.request.POST.get('Negotiate') == 'on':
                booking.price = booking.negotiationPrice
            else:
                booking.negotiationRequest = False
            booking.save()
        return redirect('Owner:RequestList')

class OwnerFeedback(generic.CreateView):
    form_class = forms.GetFeedback
    model = omodels.RenterFeedback
    template_name = "Owner/RenterFeedback.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        BookingDetails = bmodels.Booking.objects.get(
                pk=self.kwargs.get('pk')
                )
        context['BookingDetails'] = BookingDetails
        print(BookingDetails.vehicle.VehicleRegistrationNumber)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.booking = bmodels.Booking.objects.get(
            pk = self.kwargs.get('pk')
        )
        self.object.save()
        return super().form_valid(form)

class ReportAccident(generic.CreateView):
    form_class = forms.AccidentReport
    model = models.Accident
    template_name = "Owner/ReportAccident.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        vehicle = models.Vehicle.objects.get(
                pk=self.kwargs.get('pk')
                )
        context['vehicle'] = vehicle
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.vehicle = models.Vehicle.objects.get(
                pk=self.kwargs.get('pk')
                )
        self.object.save()
        return super().form_valid(form)

class EnableVehicle(generic.DetailView):
    model = models.Vehicle
    template_name = 'Owner/EnableVehicle.html'
    context_object_name = "vehicle_detail"

    def post(self, request, *args, **kwargs):
        accidentVehicle = models.Accident.objects.filter(
            vehicle__pk = self.kwargs.get("pk")
        ).filter(
            disabled = True
        )
        accidentVehicle.update(disabled = False)
        return redirect('Owner:OwnerVehicles')

RentVehicle/Vehicle/views.py
#https://simpleisbetterthancomplex.com/tutorial/2016/11/28/how-to-filter-querysets-dynamically.html
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from . import models, forms
from django.http import Http404
from dropdowndb.models import tempZipcode, ZipCode
from django.http import HttpResponseRedirect
from Booking import models as bmodels
from dropdowndb import models as dmodels

# Create your views here.
class VehicleList(generic.ListView):
    model = models.Vehicle
    template_name = "Vehicle/vehicle_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form
        return context

    def get_queryset(self):
        try:
            #self.vehicle = super().get_queryset()
            self.form = forms.CreateFilter()
            self.filter = models.Filter.objects.get(user=None)

            self.vehicles = models.Vehicle.objects.filter()
            try:
                Accident_vehicle = models.Accident.objects.filter(
                    disabled = True
                ).values()
                if len(Accident_vehicle) > 0:
                    for av in Accident_vehicle:
                        self.vehicles = self.vehicles.exclude(
                        pk = av['vehicle_id']
                        )
            except:
                pass
            if self.filter.zipcode:
                print('1')
                self.vehicles = self.vehicles.filter(
                    zipcode__zipcode = self.filter.zipcode
                )
            if self.filter.make:
                print('2')
                self.vehicles = self.vehicles.filter(
                    make__make = self.filter.make.make
                )
            if self.filter.color:
                print('3')
                self.vehicles = self.vehicles.filter(
                    color__color = self.filter.color
                )
            if self.filter.StartPrice and self.filter.EndPrice:
                print('4')
                print(self.filter.StartPrice)
                self.vehicles = self.vehicles.filter(
                    price__gte = self.filter.StartPrice

                ).filter(
                price__lte = self.filter.EndPrice
                )
            elif self.filter.EndPrice:
                print('5')
                self.vehicles = self.vehicles.filter(
                    price__lte = self.filter.EndPrice
                )
            elif self.filter.StartPrice:
                print('8')
                self.vehicles = self.vehicles.filter(
                    price__gte = self.filter.EndPrice
                )
            if self.filter.rating:
                print('6')
                self.vehicles = self.vehicles.filter(
                    rating__rating__gte = self.filter.rating.rating
                )
            if self.filter.style:
                print('7')
                self.vehicles = self.vehicles.filter(
                    style__style = self.filter.style
                )
            if self.filter.bookingDate:
                pk = bmodels.Booking.objects.filter(bookingDate = self.filter.bookingDate)
                pk = pk.filter(bookingStatus = dmodels.BookingStatus.objects.get(pk=3)).values()
                print('8')
                for veh in pk:
                    print(veh['vehicle_id'])
                    self.vehicles = self.vehicles.exclude(
                        pk = veh['vehicle_id']
                    )
                print('8')
        except Exception as e:
            print (type(e))
            return ""
        else:
            return self.vehicles.all()

    def post(self, request, *args, **kwargs):
        filter_form = forms.CreateFilter(data = request.POST)
        if filter_form.is_valid():
            filterForm = filter_form.save(commit=False)
            filter = models.Filter.objects.filter(user=None)
            filter.update(zipcode=filterForm.zipcode,
                          make = filterForm.make,
                          color=filterForm.color,
                          style=filterForm.style,
                          StartPrice=filterForm.StartPrice,
                          EndPrice=filterForm.EndPrice,
                          rating=filterForm.rating,
                          bookingDate=filterForm.bookingDate
                          )
        return redirect('Vehicle:all')

class VehicleDetails(generic.DetailView):
    model = models.Vehicle
    template_name = "Vehicle/Vehicle_Detail.html"
    context_object_name = "vehicle_detail"

RentVehicle/Owner/templates/Owner/EnableVehicle.html
{% extends "Owner/owner_base.html" %}

{% block Navigation %}
	<a class="nav-item nav-link" href="{% url 'Owner:CreateVehicle' %}" class="btn btn-simple">Add Vehicle</a>
{% endblock %}

  {% block ownervehicles %}


      <h1>Following is the details of your Vehicle</h1>

			<img src="{{vehicle_detail.image.url}}" alt="" height="250" width="300">

      <table>
        <tr>
          <td></td>
          <td>
            <p>Make : {{vehicle_detail.make.make}}</p>
          </td>
          <td> <p>      </p> </td>
          <td>
            <p>Model : {{vehicle_detail.model.makemodel}}</p>
          </td>
        </tr>

          <tr>
            <td></td>
            <td>
              <p>Vehicle Registration Number : {{vehicle_detail.VehicleRegistrationNumber}}</p>
            </td>
            <td> <p>      </p> </td>

            <td>
              <p>Style : {{vehicle_detail.style.style}}</p>
            </td>
          </tr>

            <tr>
              <td></td>
              <td>
                <p>Year : {{vehicle_detail.year}}</p>
              </td>
              <td> <p>      </p> </td>

              <td>
                <p>Color : {{vehicle_detail.color.color}}</p>
              </td>
            </tr>

              <tr>
                <td></td>
                <td>
                  <p>Price : {{vehicle_detail.price}}</p>
                </td>
                <td> <p>      </p> </td>

                <td>
                  <p>Security Deposit : {{vehicle_detail.securityDeposit}}</p>
                </td>
              </tr>

                <tr>
                  <td></td>
                  <td>
                    <p>Insurance : {{vehicle_detail.insurance}}</p>
                  </td>
                  <td> <p>      </p> </td>

                  <td>
                    <p>EZpass : {{vehicle_detail.EZpass}}</p>
                  </td>
                </tr>

                  <tr>
                    <td></td>
                    <td>
                      <p>Description : {{vehicle_detail.description}}</p>
                    </td>
                    <td> <p>      </p> </td>

                    <td>
                      <p>Terms and Conditions : {{vehicle_detail.TermsAndConditions}}</p>
                    </td>
                  </tr>

                    <tr>
                      <td></td>
                      <td>
                        <p>Rating : {{vehicle_detail.rating}}</p>
                      </td>
                      <td> <p>      </p> </td>

                    </tr>
      </table>
			<form method="POST" action="{% url 'Owner:EnableVehicle' pk=vehicle_detail.pk%}" id="groupForm">
		  	{% csrf_token %}
		  	<button type="submit" class="btn btn-primary btn-large">Get the vehicle back on road?</button>
		  </form>
			{% endblock %}

RentVehicle/Owner/templates/Owner/OwnerVehicle_Detail.html
{% extends "Owner/owner_base.html" %}

{% block Navigation %}
	<a class="nav-item nav-link" href="{% url 'Owner:CreateVehicle' %}" class="btn btn-simple">Add Vehicle</a>
{% endblock %}

  {% block ownervehicles %}


      <h1>Following is the details of your Vehicle</h1>

			<img src="{{vehicle_detail.image.url}}" alt="" height="250" width="300">

      <table>
        <tr>
          <td></td>
          <td>
            <p>Make : {{vehicle_detail.make.make}}</p>
          </td>
          <td> <p>      </p> </td>
          <td>
            <p>Model : {{vehicle_detail.model.makemodel}}</p>
          </td>
        </tr>

          <tr>
            <td></td>
            <td>
              <p>Vehicle Registration Number : {{vehicle_detail.VehicleRegistrationNumber}}</p>
            </td>
            <td> <p>      </p> </td>

            <td>
              <p>Style : {{vehicle_detail.style.style}}</p>
            </td>
          </tr>

            <tr>
              <td></td>
              <td>
                <p>Year : {{vehicle_detail.year}}</p>
              </td>
              <td> <p>      </p> </td>

              <td>
                <p>Color : {{vehicle_detail.color.color}}</p>
              </td>
            </tr>

              <tr>
                <td></td>
                <td>
                  <p>Price : {{vehicle_detail.price}}</p>
                </td>
                <td> <p>      </p> </td>

                <td>
                  <p>Security Deposit : {{vehicle_detail.securityDeposit}}</p>
                </td>
              </tr>

                <tr>
                  <td></td>
                  <td>
                    <p>Insurance : {{vehicle_detail.insurance}}</p>
                  </td>
                  <td> <p>      </p> </td>

                  <td>
                    <p>EZpass : {{vehicle_detail.EZpass}}</p>
                  </td>
                </tr>

                  <tr>
                    <td></td>
                    <td>
                      <p>Description : {{vehicle_detail.description}}</p>
                    </td>
                    <td> <p>      </p> </td>

                    <td>
                      <p>Terms and Conditions : {{vehicle_detail.TermsAndConditions}}</p>
                    </td>
                  </tr>

                    <tr>
                      <td></td>
                      <td>
                        <p>Rating : {{vehicle_detail.rating}}</p>
                      </td>
                      <td> <p>      </p> </td>

                    </tr>
      </table>
			<a href="{% url "Owner:ReportAccident" pk=vehicle_detail.pk%}"><input type="submit" name="" value="Report Accident"></a>


  {% endblock %}

RentVehicle/Owner/templates/Owner/OwnerVehicle_List.html
{% extends "Owner/owner_base.html" %}

{% block Navigation %}
	<a class="nav-item nav-link" href="{% url 'Owner:CreateVehicle' %}" class="btn btn-simple">Add Vehicle</a>
	<a class="nav-item nav-link" href="{% url "Owner:RequestList" %}" class="btn btn-simple">Requests</a>
	<a class="nav-item nav-link" href="{% url "Booking:OwnerBookingList" %}" class="btn btn-simple">Booking</a>
{% endblock %}

{% block ownervehicles %}
<div class="rikhav">
  <h3>Following is the list of all the Vehicles</h3>
  <div class="row">
    {% for vehicles in vehicle_list %}
      <div class="col-lg-6 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Owner:VehicleDetails' VehicleRegistrationNumber=vehicles.VehicleRegistrationNumber pk=vehicles.pk%}">{{vehicles.make.make}} {{vehicles.model.makemodel}}</a>
              <ul>
                <h6 style="padding-right: 45px;"><li>{{vehicles.VehicleRegistrationNumber}}	</li></h6>
								<h6 style="padding-right: 45px;"><li>Rental Price: - {{vehicles.price}}	</li></h6>
								<h6 style="padding-right: 45px;"><li>Security Deposit: - {{vehicles.securityDeposit}}	</li></h6>
              </ul>
            </td>
            <td>
              <img src="{{vehicles.image.url}}" alt="" height="200" width="240">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>
	<div class="rikhav">
		<h3>Following is the list of disabled the Vehicles</h3>
	<div class="row">
		{% for vehicles in vehicle %}
			<div class="col-lg-6 boxy">
				<table>
					<tr>
						<td>
							<h4><a href="{% url 'Owner:EnableVehicle' pk=vehicles.pk%}">{{vehicles.make.make}} {{vehicles.model.makemodel}}</a>
							<ul>
								<h6 style="padding-right: 45px;"><li>{{vehicles.VehicleRegistrationNumber}}	</li></h6>
								<h6 style="padding-right: 45px;"><li>Rental Price: - {{vehicles.price}}	</li></h6>
								<h6 style="padding-right: 45px;"><li>Security Deposit: - {{vehicles.securityDeposit}}	</li></h6>
							</ul>
						</td>
						<td>
							<img src="{{vehicles.image.url}}" alt="" height="200" width="240">
						</td>
					</tr>
				</table>
			</div>
		{% endfor %}
	</div>

</div>

{% endblock %}

RentVehicle/Owner/templates/Owner/RenterFeedback.html
<!DOCTYPE html>
{% extends "Owner/owner_base.html" %}
{% load bootstrap3 %}

  {% block ownervehicles %}
  <img src="{{BookingDetails.vehicle.image.url}}" alt="" height="250" width="300">
  <h4>{{BookingDetails.vehicle.make.make}} {{BookingDetails.vehicle.model.makemodel}}</h4>
  <form method="POST" action="{% url 'Owner:OwnerFeedback' VehicleRegistrationNumber=BookingDetails.vehicle.VehicleRegistrationNumber pk=BookingDetails.pk%}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Submit</button>
  	{% endbuttons %}
  </form>
{% endblock %}

RentVehicle/Owner/templates/Owner/request_details.html
{% extends "Owner/owner_base.html" %}

{% load bootstrap3 %}

{% block Navigation %}
	<a class="nav-item nav-link" href="{% url 'Owner:CreateVehicle' %}" class="btn btn-simple">Add Vehicle</a>
{% endblock %}

{% block ownervehicles %}

  <h1>Following is the details of your Request</h1>
  <img src="{{booking.vehicle.image.url}}" alt="" height="250" width="300">
  <h3>Car Name: - {{booking.vehicle.make.make}}</h3>
  <h3>Car Model: - {{booking.vehicle.model.makemodel}}</h3>
  <h5>{{booking.bookingDate}}</h5>
  <h5>Booking price: - {{booking.price}}</h5>
  <h5>Request Status: - {{booking.requestStatus}}</h5>
  <h5>Booking Status: - {{booking.bookingStatus}}</h5>

  <form action="{% url "Owner:RequestDetails" pk=booking.pk%}" method="post">

    {% csrf_token %}
		<div class="row">
			<div class="col-lg-4 boxy">
				{% for f in form %}
					{% if negotiationRequest == True %}
						<h5><input type="checkbox" name = "Negotiate"> Accept Negotiation?</h5>
					{% endif %}
    			<h5>Your Response: - {{f}}</h5>
				{% endfor	 %}
			</div>
		</div>
    <input type="submit" value="Submit">

  </form>
	{% if feedback.count %}
		<h3>Following are the ratings available for the requested user</h3>
		{% for f in feedback %}
			<h5>Rating: - {{f.rating}}</h5>
			<h5>Description: - {{f.description}}</h5>
		{% endfor %}
	{% else %}
		<h5>No ratings available for the requested used</h5>
	{% endif %}
{% endblock %}

RentVehicle/Owner/templates/Owner/request_list.html
{% extends "Owner/owner_base.html" %}

{% block Navigation %}
	<a class="nav-item nav-link" href="{% url 'Owner:CreateVehicle' %}" class="btn btn-simple">Add Vehicle</a>
{% endblock %}

{% block ownervehicles %}

<div class="rikhav">
  <h3>Following is the list of all the Request</h3>
  <div class="row">
    {% for request in request_list %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Owner:RequestDetails' pk=request.pk%}">{{request.vehicle.make.make}} {{request.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{request.bookingDate}}</li></h6>
                  {% if request.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{request.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{request.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{request.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}