RentVehicle/Booking/urls.py
from django.urls import path
from . import views

app_name='Booking'

urlpatterns = [
    path('<VehicleRegistrationNumber>/<int:pk>', views.CreateBooking.as_view(), name="CreateBooking"),
    path('RenterBooking/',views.RenterBookingList.as_view(), name="RenterBookingList"),
    path('OwnerBookingList/',views.OwnerBookingList.as_view(), name="OwnerBookingList"),
    path('<int:pk>', views.RenterBookingDetails.as_view(), name='RenterBookingDetails'),
    path('Owner/Booking/Details<int:pk>', views.OwnerBookingDetails.as_view(), name='OwnerBookingDetails'),
    path('OldBooking/Details/<int:pk>', views.OldBookingDetails.as_view(), name='OldBookingDetails'),
    path('<int:pk>/SelectPayment', views.SelectPayment.as_view(), name='SelectPayment'),
    path('MakePayment/PayByCard/<int:pk>', views.CardPayment.as_view(), name='CardPayment'),
    path('MakePayment/PayByCheck/<int:pk>', views.CheckPayment.as_view(), name='CheckPayment'),
]

RentVehicle/Owner/urls.py
from django.urls import path
from . import views

app_name = 'Owner'

urlpatterns = [
    path("OwnerVehicles/", views.ListOwnerVehicles.as_view(), name="OwnerVehicles"),
    path("AddVehicle/",views.CreateVehicle.as_view(),name = 'CreateVehicle'),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    path("requests/", views.RequestList.as_view(), name = "RequestList"),
    path('requests/<int:pk>', views.RequestDetails.as_view(), name='RequestDetails'),
    path("Owner/Feedback/<VehicleRegistrationNumber>/<int:pk>",views.OwnerFeedback.as_view(), name = "OwnerFeedback"),
    path("Report/Accident/<int:pk>",views.ReportAccident.as_view(), name = "ReportAccident"),
    path("Enable/The/Vehicle/<int:pk>",views.EnableVehicle.as_view(), name = "EnableVehicle"),
]

RentVehicle/RentVehicle/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name = 'home'),
    path('SignUp/',views.SignUp, name = 'SignUp'),
    path('LogIn/',views.LogIn, name = 'LogIn'),
    path("accounts/", include("Account.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('vehicle/',include("Vehicle.urls", namespace="vehicles")),
    path("owner/", include("Owner.urls", namespace="owner")),
    path("renter/", include("Renter.urls", namespace="renter")),
    path("booking/", include("Booking.urls", namespace="booking")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RentVehicle/Renter/urls.py
from django.urls import path
from . import views

app_name='Renter'

urlpatterns = [
    path('', views.ListAvailableVehicles.as_view(), name="AvailableVehicles"),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    path("RenterFeedback/<VehicleRegistrationNumber>/<int:pk>",views.RenterFeedback.as_view(), name = "RenterFeedback"),
]

RentVehicle/Booking/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from Vehicle.models import Vehicle
from dropdowndb.models import BookingStatus, RequestStatus

# Create your models here.
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    bookingDate = models.DateField()
    bookingDoneOn = models.DateField(auto_now=True)
    price = models.DecimalField(max_digits=6,decimal_places = 2)
    additionalDriverName = models.CharField(max_length=256,null=True)
    additionalDriverLicense = models.CharField(max_length=15,null=True)
    requestStatus = models.ForeignKey(RequestStatus, on_delete=models.CASCADE,null=True)
    bookingStatus = models.ForeignKey(BookingStatus, on_delete=models.CASCADE,null=True)
    negotiationRequest = models.BooleanField(default=False)
    negotiationPrice = models.DecimalField(max_digits=6,decimal_places = 2)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "Booking:RenterBookingDetails",
            kwargs={
                "pk": self.pk
            }
        )

class PaymentDetailsCard(models.Model):
    cardHolderName = models.CharField(max_length=256)
    cardNumber = models.PositiveIntegerField()
    cardCVV = models.PositiveIntegerField()
    expDate = models.CharField(max_length=5)
    zipCode = models.CharField(max_length=5)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)

    def __str__(self):
        return self.cardHolderName

    def get_absolute_url(self):
        return reverse(
            "Booking:RenterBookingDetails",
            kwargs={
                "pk": self.booking.pk
            }
        )

class PaymentDetailsCheck(models.Model):
    Bank = models.CharField(max_length=256)
    CheckNumber = models.PositiveIntegerField()
    RoutingNumber = models.PositiveIntegerField()
    CheckDate = models.CharField(max_length=5)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)

    def __str__(self):
        return self.cardHolderName

    def get_absolute_url(self):
        return reverse(
            "Booking:RenterBookingDetails",
            kwargs={
                "pk": self.booking.pk
            }
        )

RentVehicle/Booking/forms.py
# https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms
from . import models
from django import forms
import datetime
from Vehicle import models as vmodels
from dropdowndb import models as dmodels

class CreateBooking(forms.ModelForm):
    class Meta:
        fields = ('bookingDate','additionalDriverName','additionalDriverLicense','negotiationPrice')
        model = models.Booking

    def __init__(self,*args,**kwargs):
        self.vehNum = kwargs.pop('VehNum')
        self.user = kwargs.pop('user')
        super(CreateBooking,self).__init__(*args, **kwargs)
        self.fields['bookingDate'].initial = vmodels.Filter.objects.get(user=self.user).bookingDate
        self.fields['additionalDriverName'].required = False
        self.fields['additionalDriverLicense'].required = False
        self.fields['negotiationPrice'].required = False

    def clean_bookingDate(self):
        print("Cleaning Booking")
        bookingdate = self.cleaned_data.get('bookingDate')
        if(bookingdate < datetime.date.today()):
            raise forms.ValidationError("Booking date has to be future date")

        past_booking = models.Booking.objects.filter(
            vehicle= vmodels.Vehicle.objects.get(VehicleRegistrationNumber=self.vehNum)
        ).filter(
            bookingDate=bookingdate
        ).filter(
            bookingStatus = dmodels.BookingStatus.objects.get(statusId = 3)
        )
        if past_booking.count()>0:
            raise forms.ValidationError("Vehicle not available on this date")
        return bookingdate

class CreateCardPayment(forms.ModelForm):
    class Meta:
        exclude = ['booking']
        model = models.PaymentDetailsCard

class CreateCheckPayment(forms.ModelForm):
    class Meta:
        exclude = ['booking']
        model = models.PaymentDetailsCheck

RentVehicle/Booking/views.py
from django.shortcuts import render, redirect
from django.views import generic
from . import models
from . import forms
from django.http import Http404
from Vehicle import models as vmodels
from Account import models as amodels
from dropdowndb import models as dmodels
from Booking import models as bmodels
from django.core.mail import send_mail,get_connection
from django.conf import settings
from django.views.generic.edit import ModelFormMixin
import datetime
from Renter import models as rmodels
from Owner import models as omodels

class CreateBooking(generic.CreateView):
    form_class = forms.CreateBooking
    model = models.Booking
    template_name = "Booking/booking_form.html"

    def get_form_kwargs(self):
        kwargs = super(CreateBooking, self).get_form_kwargs()
        #kwargs['VehNum'] = self.kwargs.get('VehicleRegistrationNumber') # the trick!
        kwargs.update({'VehNum': self.kwargs.get('VehicleRegistrationNumber')})
        kwargs.update({'user': self.request.user})
        print("in get_form_kwargs")
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["VRnum"] = self.kwargs.get('VehicleRegistrationNumber')
        print(self.kwargs.get('VehicleRegistrationNumber'))
        context["VRid"] = self.kwargs.get("pk")
        context['vehicle'] = vmodels.Vehicle.objects.get(VehicleRegistrationNumber=self.kwargs.get('VehicleRegistrationNumber'))
        return context

    def form_valid(self, form):
        print("in form_valid")
        self.object = form.save(commit=False)
        vehicle = vmodels.Vehicle.objects.get(VehicleRegistrationNumber=self.kwargs.get('VehicleRegistrationNumber'))
        self.object.vehicle = vehicle
        self.object.user = self.request.user
        veh_state = dmodels.ZipCode.objects.get(zipcode=vehicle.zipcode).state
        staterate = dmodels.StateTax.objects.get(state = veh_state)
        self.object.price = (vehicle.price * staterate.rate) + vehicle.securityDeposit
        self.object.requestStatus = dmodels.RequestStatus.objects.get(statusId = 1)
        self.object.bookingStatus = dmodels.BookingStatus.objects.get(statusId = 1)
        if self.request.POST.get('negotiate') == 'on':
            self.object.negotiationRequest = True
        else:
            self.object.negotiationRequest = False
            self.object.negotiationPrice = 0
        self.object.save()
        return super().form_valid(form)

    # def post(self, request, *args, **kwargs):
    #     book_form = forms.CreateBooking(data = request.POST)
    #     if book_form.is_valid():
    #         self.object = book_form.save(commit=False)
    #         self.object.user = self.request.user
    #         vehicle = vmodels.Vehicle.objects.get(VehicleRegistrationNumber=self.kwargs.get('VehicleRegistrationNumber'))
    #         self.object.vehicle = vehicle
    #         self.object.price = vehicle.price + vehicle.securityDeposit
    #         self.object.requestStatus = dmodels.RequestStatus.objects.get(statusId = 1)
    #         self.object.bookingStatus = dmodels.BookingStatus.objects.get(statusId = 1)
    #         self.object.save()
    #     return redirect('Booking:BookingList')

class RenterBookingList(generic.ListView):
    model = models.Booking
    template_name = 'Booking/RenterBooking_List.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['AcceptedBooking'] = models.Booking.objects.filter(
                user = self.request.user
            ).filter(
                requestStatus = dmodels.RequestStatus.objects.get(pk=3)
            ).filter(
                bookingStatus = dmodels.BookingStatus.objects.get(pk=1)
            ).filter(
                bookingDate__gte = datetime.date.today()
            )
        context['RejectedBookingOwner'] = models.Booking.objects.filter(
                user = self.request.user
            ).filter(
                requestStatus = dmodels.RequestStatus.objects.get(pk=2)
            ).filter(
                bookingDate__gte = datetime.date.today()
            )
        context['RejectedBookingRenter'] = models.Booking.objects.filter(
                user = self.request.user
            ).filter(
                requestStatus = dmodels.RequestStatus.objects.get(pk=3)
            ).filter(
                bookingStatus = dmodels.BookingStatus.objects.get(pk=2)
            ).filter(
                bookingDate__gte = datetime.date.today()
            )
        context['CompletedBooking'] = models.Booking.objects.filter(
                user = self.request.user
            ).filter(
                requestStatus = dmodels.RequestStatus.objects.get(pk=3)
            ).filter(
                bookingStatus = dmodels.BookingStatus.objects.get(pk=3)
            ).filter(
                bookingDate__gte = datetime.date.today()
            ).filter(
                bookingDate__gte = datetime.date.today()
            )
        context['OldBooking'] = models.Booking.objects.filter(
                user = self.request.user
            ).filter(
                requestStatus = dmodels.RequestStatus.objects.get(pk=3)
            ).filter(
                bookingStatus = dmodels.BookingStatus.objects.get(pk=3)
            ).filter(
                bookingDate__lte = datetime.date.today()
            )
        return context

    def get_queryset(self):
        try:
            self.bookings = bmodels.Booking.objects.filter(
                user = self.request.user
            ).filter(
                requestStatus = dmodels.RequestStatus.objects.get(pk=1)
            ).filter(
                bookingDate__gte = datetime.date.today()
            )
        except Exception as e:
            print (type(e))
            return ""
        else:
            return self.bookings.all()

class OwnerBookingList(generic.ListView):
    model = models.Booking
    template_name = 'Booking/OwnerBooking_List.html'

    def get_queryset(self):
        try:
            self.bookings = bmodels.Booking.objects.filter(
                vehicle__user = self.request.user
            )
            self.bookings = self.bookings.filter(
                bookingStatus = dmodels.BookingStatus.objects.get(pk=3)
            )
        except Exception as e:
            print (type(e))
            return ""
        else:
            return self.bookings.all()

class RenterBookingDetails(generic.DetailView):
    model = models.Booking
    template_name = "Booking/renterBooking_Detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        booking = models.Booking.objects.get(pk=self.kwargs.get('pk'))
        if booking.requestStatus == dmodels.RequestStatus.objects.get(pk=3):
            context["Owneraccepted"] = True
        else:
            context["Owneraccepted"] = False
        if booking.bookingStatus == dmodels.BookingStatus.objects.get(pk=2):
            context["renterRejected"] = False
        else:
            context["renterRejected"] = True
        if booking.bookingStatus == dmodels.BookingStatus.objects.get(pk=3):
            context["booked"] = True
        else:
            context["booked"] = False
        return context

    def post(self, request, *args, **kwargs):
        booking = models.Booking.objects.filter(pk=self.kwargs.get('pk'))
        booking.update(bookingStatus = dmodels.BookingStatus.objects.get(pk=2))
        return redirect('Booking:RenterBookingList')

class SelectPayment(generic.DetailView):
    template_name = 'Booking/SelectPayment.html'
    model = models.Booking

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        booking = models.Booking.objects.get(pk=self.kwargs.get('pk'))
        context["pk"] = booking.pk
        return context

class CardPayment(generic.CreateView):
    form_class = forms.CreateCardPayment
    model = models.PaymentDetailsCard
    template_name = "Booking/Card_form.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        curr_booking = models.Booking.objects.get(pk=self.kwargs.get('pk'))
        curr_booking.bookingStatus = dmodels.BookingStatus.objects.get(statusId=3)
        curr_booking.save()
        self.object.booking = curr_booking
        self.object.save()
        EmailSender(curr_booking,[curr_booking.user.email],[curr_booking.vehicle.user.email])
        return super().form_valid(form)

class CheckPayment(generic.CreateView):
    form_class = forms.CreateCheckPayment
    model = models.PaymentDetailsCheck
    template_name = "Booking/Check_form.html"
    def form_valid(self, form):
        self.object = form.save(commit=False)
        curr_booking = models.Booking.objects.get(pk=self.kwargs.get('pk'))
        curr_booking.bookingStatus = dmodels.BookingStatus.objects.get(statusId=3)
        curr_booking.save()
        self.object.booking = curr_booking
        self.object.save()
        EmailSender(curr_booking)
        return super().form_valid(form)

def EmailSender(curr_booking,RenterEmail,OwnerEmail):
    my_use_tls = True
    my_host = "smtp.gmail.com"
    my_user = "rentvehicle2019@gmail.com"
    my_password = "Qwe123rty!"
    my_port = 587

    new_conn = get_connection(host=my_host,port=my_port,username=my_user,password=my_password,use_tls=my_use_tls)

    subject = 'Booking Confirmation'
    message_renter = 'Thank you for renting the car. Following are the booking details: -\nCar: - {}\nBooking Date: - {}\nBooking Price: - {}\n'.format(curr_booking.vehicle,curr_booking.bookingDate,curr_booking.price)
    message_owner = 'Booking are the details for the booking done for your car: -\nCar: - {}\nBooking Date: - {}\nBooking Price: - {}\nAmount creditted to you is: -{}'.format(curr_booking.vehicle,curr_booking.bookingDate,curr_booking.price,str(round(int(curr_booking.price)*0.9,2)))
    email_from = my_user

RentVehicle/Booking/templates/Booking/OwnerBooking_Detail.html
{% extends "Booking/ownerbooking_base.html" %}

  {% block booking %}


      <h1>Following is the details of your booking</h1>
      <div class="BookingDetails">
        <img src="{{booking.vehicle.image.url}}" alt="" height="250" width="300">
        <h2>Car Name: - {{booking.vehicle.make.make}}</h2>
        <h2>Car Model: - {{booking.vehicle.model.makemodel}}</h2>
        <h4>Booking Date: - {{booking.bookingDate}}</h4>
        {% if booking.negotiationRequest %}
          <h4>Negotiation price: - {{booking.negotiationPrice}}</h4>
        {% else %}
          <h4>Booking price: - {{booking.price}}</h4>
        {% endif %}
        <p></p>
        <h4>Request Status: - {{booking.requestStatus}}</h4>
        <h4>Booking Status: - {{booking.bookingStatus}}</h4>
      {% if feedBackGiven %}
        <h4>Feedback</h4>
        <a href="{% url "Owner:OwnerFeedback" VehicleRegistrationNumber=booking.vehicle.VehicleRegistrationNumber pk=booking.pk%}"><input type="submit" name="" value="Give Feedback"></a>
      {% else %}
        <h3>Feedback Given is</h3>
        <h4>Rating: - {{feedback.rating}}</h4>
        <h4>Description: - {{feedback.description}}</h4>
      {% endif %}
      </div>
  {% endblock %}

RentVehicle/Booking/templates/Booking/OwnerBooking_List.html
{% extends "Booking/ownerbooking_base.html" %}

{% block booking %}

<div class="rikhav">
  <h3>Following is the list of all the Booking</h3>
  <div class="row">
    {% for bookings in booking_list %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:OwnerBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

RentVehicle/Booking/templates/Booking/RenterBooking_List.html
{% extends "Booking/renterbooking_base.html" %}

{% block booking %}
<div class="rikhav">
  <h3>In Process Bookings</h3>
  <div class="row">
    {% for bookings in booking_list %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:RenterBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

<div class="rikhav">
  <h3>Bookings Accepted by Owner</h3>
  <div class="row">
    {% for bookings in AcceptedBooking %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:RenterBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

<div class="rikhav">
  <h3>Bookings Completed</h3>
  <div class="row">
    {% for bookings in CompletedBooking %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:RenterBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

<div class="rikhav">
  <h3>Bookings Rejected by Owner</h3>
  <div class="row">
    {% for bookings in RejectedBookingOwner %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:RenterBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

<div class="rikhav">
  <h3>Bookings Cancelled by Renter</h3>
  <div class="row">
    {% for bookings in RejectedBookingRenter %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:RenterBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>

<div class="rikhav">
  <h3>Past Completed Bookings</h3>
  <div class="row">
    {% for bookings in OldBooking %}
      <div class="col-lg-4 boxy">
        <table>
          <tr>
            <td>
              <h4><a href="{% url 'Booking:OldBookingDetails' pk=bookings.pk%}">{{bookings.vehicle.make.make}} {{bookings.vehicle.model.makemodel}}</a></h4>
              <ul>
                <h6><li>Booking Date: - {{bookings.bookingDate}}</li></h6>
                  {% if bookings.negotiationRequest %}
                    <h6><li>Negotiation Price: - {{bookings.negotiationPrice}}</li></h6>
                  {% else %}
                    <h6><li>Booking Price: - {{bookings.price}}</li></h6>
                  {% endif %}
              </ul>
            </td>
            <td>
              <img src="{{bookings.vehicle.image.url}}" alt="" height="70" width="84">
            </td>
          </tr>
        </table>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

RentVehicle/Booking/templates/Booking/SelectPayment.html
{% extends "Booking/renterbooking_base.html" %}

{% block booking %}

<div class="jumbotron">
  <h1><font color = "black">Kindly Select The Payment Method</font></h1>
  <a href="{%url 'Booking:CardPayment' pk=pk%}">
    <button type="button" name="btn btn-success">
      Pay by Card
    </button>
  </a>
  <a href="{%url 'Booking:CheckPayment' pk=pk%}">
    <button type="button" name="btn btn-success">
      Pay By Check
    </button>
  </a>

</div>

{% endblock %}

RentVehicle/Booking/templates/Booking/oldBooking_Detail.html
{% extends "Booking/renterbooking_base.html" %}

  {% block booking %}


      <h1>Following is the details of your booking</h1>
      <div class="BookingDetails">
        <img src="{{booking.vehicle.image.url}}" alt="" height="250" width="300">
        <h2>Car Name: - {{booking.vehicle.make.make}}</h2>
        <h2>Car Model: - {{booking.vehicle.model.makemodel}}</h2>
        <h4>Booking Date: - {{booking.bookingDate}}</h4>
        {% if booking.negotiationRequest %}
          <h4>Negotiation price: - {{booking.negotiationPrice}}</h4>
        {% else %}
          <h4>Booking price: - {{booking.price}}</h4>
        {% endif %}
        <p></p>
        <h4>Request Status: - {{booking.requestStatus}}</h4>
        <h4>Booking Status: - {{booking.bookingStatus}}</h4>
      {% if feedBackGiven %}
        <h4>Feedback</h4>
        <a href="{% url "Renter:RenterFeedback" VehicleRegistrationNumber=booking.vehicle.VehicleRegistrationNumber pk=booking.pk%}"><input type="submit" name="" value="Give Feedback"></a>
      {% else %}
        <h3>Feedback Given is</h3>
        <h4>Rating: - {{feedback.rating}}</h4>
        <h4>Description: - {{feedback.description}}</h4>
      {% endif %}
      </div>
  {% endblock %}