RentVehicle/Booking/urls.py
from django.urls import path
from . import views

app_name='Booking'

urlpatterns = [
    path('<VehicleRegistrationNumber>/<int:pk>', views.CreateBooking.as_view(), name="CreateBooking"),
    path('RenterBooking/',views.RenterBookingList.as_view(), name="RenterBookingList"),
    path('OwnerBookingList/',views.OwnerBookingList.as_view(), name="OwnerBookingList"),
    path('<int:pk>', views.RenterBookingDetails.as_view(), name='RenterBookingDetails'),
    path('Owner/Booking/Details<int:pk>', views.OwnerBookingDetails.as_view(), name='OwnerBookingDetails'),
    path('OldBooking/Details/<int:pk>', views.OldBookingDetails.as_view(), name='OldBookingDetails'),
    path('<int:pk>/SelectPayment', views.SelectPayment.as_view(), name='SelectPayment'),
    path('MakePayment/PayByCard/<int:pk>', views.CardPayment.as_view(), name='CardPayment'),
    path('MakePayment/PayByCheck/<int:pk>', views.CheckPayment.as_view(), name='CheckPayment'),
]

RentVehicle/Owner/urls.py
from django.urls import path
from . import views

app_name = 'Owner'

urlpatterns = [
    path("OwnerVehicles/", views.ListOwnerVehicles.as_view(), name="OwnerVehicles"),
    path("AddVehicle/",views.CreateVehicle.as_view(),name = 'CreateVehicle'),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    path("requests/", views.RequestList.as_view(), name = "RequestList"),
    path('requests/<int:pk>', views.RequestDetails.as_view(), name='RequestDetails'),
    path("Owner/Feedback/<VehicleRegistrationNumber>/<int:pk>",views.OwnerFeedback.as_view(), name = "OwnerFeedback"),
    path("Report/Accident/<int:pk>",views.ReportAccident.as_view(), name = "ReportAccident"),
    path("Enable/The/Vehicle/<int:pk>",views.EnableVehicle.as_view(), name = "EnableVehicle"),
]

RentVehicle/RentVehicle/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage, name = 'home'),
    path('SignUp/',views.SignUp, name = 'SignUp'),
    path('LogIn/',views.LogIn, name = 'LogIn'),
    path("accounts/", include("Account.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('vehicle/',include("Vehicle.urls", namespace="vehicles")),
    path("owner/", include("Owner.urls", namespace="owner")),
    path("renter/", include("Renter.urls", namespace="renter")),
    path("booking/", include("Booking.urls", namespace="booking")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RentVehicle/Renter/urls.py
from django.urls import path
from . import views

app_name='Renter'

urlpatterns = [
    path('', views.ListAvailableVehicles.as_view(), name="AvailableVehicles"),
    path("VehicleDetails/<VehicleRegistrationNumber>/<int:pk>",views.VehicleDetails.as_view(), name = "VehicleDetails"),
    path("RenterFeedback/<VehicleRegistrationNumber>/<int:pk>",views.RenterFeedback.as_view(), name = "RenterFeedback"),
]

RentVehicle/Renter/models.py
from django.db import models
from Vehicle.models import Vehicle
from dropdowndb import models as dmodels
from django.contrib.auth.models import User
from Booking.models import Booking
from django.urls import reverse

# Create your models here.
class VehicleFeedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE,null=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    rating = models.ForeignKey(dmodels.Rating, on_delete=models.CASCADE,null=True)
    description = models.TextField()

    def get_absolute_url(self):
        return reverse('Renter:AvailableVehicles')

RentVehicle/Renter/forms.py
from Vehicle import models
from django import forms
from dropdowndb.models import ZipCode
import datetime
from Renter import models as rmodels

class CreateFilter(forms.ModelForm):
    class Meta:
        model = models.Filter
        fields = ['zipcode', 'make', 'color', 'StartPrice', 'EndPrice', 'rating','style','bookingDate']
        help_texts = {'zipcode' : "ZipCode"}
    # def initiate(self, User):
    #

    def __init__(self, User, *args,**kwargs):
        super(CreateFilter, self).__init__(*args, **kwargs)
        try:
            filter = models.Filter.objects.get(user=User)
            print("Here")
            if filter.zipcode == None:
                self.fields['zipcode'].placeholder = "ZipCode"
            else:
                self.fields['zipcode'].initial = filter.zipcode
            self.fields['make'].initial = filter.make
            self.fields['color'].initial = filter.color
            self.fields['StartPrice'].initial = filter.StartPrice
            self.fields['EndPrice'].initial = filter.EndPrice
            self.fields['rating'].initial = filter.rating
            self.fields['style'].initial = filter.style
            if filter.bookingDate:
                if(filter.bookingDate > datetime.date.today()):
                    print("In if")
                    self.fields['bookingDate'].initial = filter.bookingDate
                else:
                    print("in else")
                    self.fields['bookingDate'].initial = datetime.date.today()
            else:
                self.fields['bookingDate'].initial = filter.bookingDate
        except:
            print("rik")
        self.fields['bookingDate'].label = 'Date'
        self.fields['zipcode'].required = False
        self.fields['make'].required = False
        self.fields['color'].required = False
        self.fields['StartPrice'].required = False
        self.fields['EndPrice'].required = False
        self.fields['rating'].required = False
        self.fields['style'].required = False
        self.fields['bookingDate'].required = False
        print("After rik")
        # filter = models.Filter.objects.get(user=None)
        # print("Here")
        # self.fields['zipcode'].initial = filter.zipcode
        # self.fields['make'].initial = filter.make
        # self.fields['color'].initial = filter.color
        # self.fields['StartPrice'].initial = filter.StartPrice
        # self.fields['EndPrice'].initial = filter.EndPrice
        # self.fields['rating'].initial = filter.rating
        # self.fields['style'].initial = filter.style
        # self.fields['bookingDate'].initial = filter.bookingDate
        # self.fields['zipcode'].required = False
        # self.fields['make'].required = False
        # self.fields['color'].required = False
        # self.fields['StartPrice'].required = False
        # self.fields['EndPrice'].required = False
        # self.fields['rating'].required = False
        # self.fields['style'].required = False
        # self.fields['bookingDate'].required = False

    def clean_bookingDate(self):
        bookingdate = self.cleaned_data.get('bookingDate')
        if(bookingdate):
            if(bookingdate < datetime.date.today()):
                raise forms.ValidationError("Booking date has to be future date")
        return bookingdate

class GetFeedback(forms.ModelForm):
    class Meta:
        model = rmodels.VehicleFeedback
        fields = ['rating','description']

RentVehicle/Renter/views.py
from django.shortcuts import render, redirect
from django.views import generic
from Vehicle import models
from Booking import models as bmodels
from dropdowndb import models as dmodels
from . import forms
from . import models as rmodels
from django.http import Http404

# Create your views here.
class ListAvailableVehicles(generic.ListView):
    model = models.Vehicle
    template_name = 'Renter/AvailableVehicle_List.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form
        return context

    def get_queryset(self):
        self.form = forms.CreateFilter(User=self.request.user)
        print("Form created")
        #self.form.initiate(self.request.user)
        self.vehicles = models.Vehicle.objects.filter()
        try:
            #self.vehicle = super().get_queryset()

            self.filter = models.Filter.objects.get(user=self.request.user)
            if self.filter.zipcode:
                print('1')
                self.vehicles = self.vehicles.filter(
                    zipcode__zipcode = self.filter.zipcode
                )
            if self.filter.make:
                print('2')
                self.vehicles = self.vehicles.filter(
                    make__make = self.filter.make.make
                )
            if self.filter.color:
                print('3')
                self.vehicles = self.vehicles.filter(
                    color__color = self.filter.color
                )
            if self.filter.StartPrice and self.filter.EndPrice:
                print('4')
                print(self.filter.StartPrice)
                self.vehicles = self.vehicles.filter(
                    price__gte = self.filter.StartPrice

                ).filter(
                price__lte = self.filter.EndPrice
                )
            elif self.filter.EndPrice:
                print('5')
                self.vehicles = self.vehicles.filter(
                    price__lte = self.filter.EndPrice
                )
            elif self.filter.StartPrice:
                print('8')
                self.vehicles = self.vehicles.filter(
                    price__gte = self.filter.EndPrice
                )
            if self.filter.rating:
                print('6')
                self.vehicles = self.vehicles.filter(
                    rating__rating__gte = self.filter.rating.rating
                )
            if self.filter.style:
                print('7')
                self.vehicles = self.vehicles.filter(
                    style__style = self.filter.style
                )
            if self.filter.bookingDate:
                pk = bmodels.Booking.objects.filter(bookingDate = self.filter.bookingDate)
                pk = pk.filter(bookingStatus = dmodels.BookingStatus.objects.get(pk=3)).values()
                print('8')
                for veh in pk:
                    print(veh['vehicle_id'])
                    self.vehicles = self.vehicles.exclude(
                        pk = veh['vehicle_id']
                    )
        except:
            return self.vehicles.all()
        else:
            return self.vehicles.all()

    def post(self, request, *args, **kwargs):
        filter_form = forms.CreateFilter(data = request.POST, User=self.request.user)
        if filter_form.is_valid():
            print("Form is valid")
            filterForm = filter_form.save(commit=False)
            try:
                filter = models.Filter.objects.filter(user=self.request.user)
                print("Filter Found")
                print(type(filter))
                filter.update(zipcode=filterForm.zipcode,
                              make = filterForm.make,
                              color=filterForm.color,
                              style=filterForm.style,
                              StartPrice=filterForm.StartPrice,
                              EndPrice=filterForm.EndPrice,
                              rating=filterForm.rating,
                              bookingDate=filterForm.bookingDate
                              )
            except:
                print(self.request.user)
                filterForm.user = self.request.user
                print("Filter saved")
                filterForm.save()
        else:
            print("Form not valid")
        return redirect('Renter:AvailableVehicles')

class VehicleDetails(generic.DetailView):
    model = models.Vehicle
    template_name = "Renter/RenterVehicle_Detail.html"
    context_object_name = "vehicle_detail"

class RenterFeedback(generic.CreateView):
    form_class = forms.GetFeedback
    model = rmodels.VehicleFeedback
    template_name = "Renter/VehicleFeedback.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        BookingDetails = bmodels.Booking.objects.get(
                pk=self.kwargs.get('pk')
                )
        context['BookingDetails'] = BookingDetails
        print(BookingDetails.vehicle.VehicleRegistrationNumber)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.vehicle = models.Vehicle.objects.get(
            VehicleRegistrationNumber = self.kwargs.get('VehicleRegistrationNumber')
            )
        self.object.booking = bmodels.Booking.objects.get(
            pk = self.kwargs.get('pk')
        )
        self.object.save()
        return super().form_valid(form)

RentVehicle/Renter/templates/Renter/AvailableVehicle_List.html
{% extends "Renter/renter_base.html" %}


{% block renter %}
<div class="filter_form">
  <form method="POST">
    {% csrf_token %}
      <div class="row">
        {% for f in form %}
        <div class="col-lg-3 boxy">{{f.label}} {{f}}</div>
        {% endfor %}
      </div>
      <p></p>
      <div class="row">
        <div class="col-lg-1 boxy"></div>
        <div class="col-lg-1 boxy"></div>
        <div class="col-lg-1 boxy"></div>
        <div class="col-lg-1 boxy"></div>
        <div class="col-lg-1 boxy"></div>
        <div class="col-lg-1 boxy"><button type="submit" class="btn btn-primary btn-large">Filter</button></div>
      </div>
  </form>
</div>

<p></p>
{% if vehicle_list.count %}
  {% for vehicles in vehicle_list %}
  <table id = 'List_Table'>
    <tr>
      <td>
        <h2><a href="{% url 'Renter:VehicleDetails' VehicleRegistrationNumber=vehicles.VehicleRegistrationNumber pk=vehicles.pk%}">{{vehicles.make.make}} {{vehicles.model.makemodel}}</a></h2>
        <ul id = 'List_Table_Detail'>
          <h3><li>{{vehicles.VehicleRegistrationNumber}}</li></h3>
        </ul>
      </td>
      <td>
        <img src="{{vehicles.image.url}}" alt="" height="250" width="300">
      </td>
    </tr>
  </table>
    {% endfor %}
  {% else %}
  <h1>No Vehicles available for the given search criteria</h1>

  {% endif %}

{% endblock %}

RentVehicle/Renter/templates/Renter/RenterVehicle_Detail.html
<!DOCTYPE html>
{% extends "Renter/renter_base.html" %}

  {% block renter %}


      <h1>Following is the details of the Vehicle</h1>

			<img src="{{vehicle_detail.image.url}}" alt="" height="250" width="300">

      <table>
        <tr>
          <td></td>
          <td>
            <p>Make : {{vehicle_detail.make.make}}</p>
          </td>
          <td> <p>      </p> </td>
          <td>
            <p>Model : {{vehicle_detail.model.makemodel}}</p>
          </td>
        </tr>

          <tr>
            <td></td>
            <td>
              <p>Vehicle Registration Number : {{vehicle_detail.VehicleRegistrationNumber}}</p>
            </td>
            <td> <p>      </p> </td>

            <td>
              <p>Style : {{vehicle_detail.style.style}}</p>
            </td>
          </tr>

            <tr>
              <td></td>
              <td>
                <p>Year : {{vehicle_detail.year}}</p>
              </td>
              <td> <p>      </p> </td>

              <td>
                <p>Color : {{vehicle_detail.color.color}}</p>
              </td>
            </tr>

              <tr>
                <td></td>
                <td>
                  <p>Price : {{vehicle_detail.price}}</p>
                </td>
                <td> <p>      </p> </td>

                <td>
                  <p>Security Deposit : {{vehicle_detail.securityDeposit}}</p>
                </td>
              </tr>

                <tr>
                  <td></td>
                  <td>
                    <p>Insurance : {{vehicle_detail.insurance}}</p>
                  </td>
                  <td> <p>      </p> </td>

                  <td>
                    <p>EZpass : {{vehicle_detail.EZpass}}</p>
                  </td>
                </tr>

                  <tr>
                    <td></td>
                    <td>
                      <p>Description : {{vehicle_detail.description}}</p>
                    </td>
                    <td> <p>      </p> </td>

                    <td>
                      <p>Terms and Conditions : {{vehicle_detail.TermsAndConditions}}</p>
                    </td>
                  </tr>

                    <tr>
                      <td></td>
                      <td>
                        <p>Rating : {{vehicle_detail.rating}}</p>
                      </td>
                      <td> <p>      </p> </td>

                    </tr>
      </table>

      <form action="{% url 'Booking:CreateBooking' VehicleRegistrationNumber=vehicle_detail.VehicleRegistrationNumber pk=vehicle_detail.pk%}" method="post">
        {%csrf_token%}
        <h6><input type="checkbox"  onchange="document.getElementById('BookCar').disabled = !this.checked;" /> Agree to Terms and Conditions</h6>
        <button type="submit" id="BookCar" class="btn btn-primary" disabled>Book Car</button>
      </form>
  {% endblock %}

RentVehicle/Renter/templates/Renter/VehicleFeedback.html
<!DOCTYPE html>
{% extends "Renter/renter_base.html" %}
{% load bootstrap3 %}

  {% block renter %}
  <img src="{{BookingDetails.vehicle.image.url}}" alt="" height="250" width="300">
  <h4>{{BookingDetails.vehicle.make.make}} {{BookingDetails.vehicle.model.makemodel}}</h4>
  <form method="POST" action="{% url 'Renter:RenterFeedback' VehicleRegistrationNumber=BookingDetails.vehicle.VehicleRegistrationNumber pk=BookingDetails.pk%}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Submit</button>
  	{% endbuttons %}
  </form>
{% endblock %}

RentVehicle/Renter/templates/Renter/renter_base.html
{% extends "base.html" %}

{% block Navigation %}
	<a class="nav-item nav-link" href="{% url 'Booking:RenterBookingList'%}" class="btn btn-simple">Booking</a>
{% endblock%}

{% block content %}
		{% block renter %}{% endblock %}
{% endblock %}